Repository the-benchmarker/web-frameworks, pull requests merged in 2018-10, with the labels that each got.

#414 Restore scala (#401, #404)
  .gitignore
  .travis.yml
  FRAMEWORKS.yml
  README.md
  dependencies.yml
  neph.yaml
  node/turbo_polka/Dockerfile
  node/turbo_polka/app.js
  node/turbo_polka/package.json
  php/laravel/composer.json
  python/cyclone/Dockerfile
  python/cyclone/requirements.txt
  python/cyclone/server.py
  python/django/requirements.txt
  tools/src/benchmarker.cr
Labels: in-review, language:scala

#433 Add muxie (go)
  .travis.yml
  FRAMEWORKS.yml
  go/muxie/Dockerfile
  go/muxie/main.go
  neph.yaml
Labels: in-review, language:go

#429 update jester to 0.4.1
  .travis.yml
  FRAMEWORKS.yml
  nim/jester/Dockerfile
  nim/jester/server_nim_jester.nimble
Labels: in-review, language:nim

#439 upgrade to swift 4
  swift/kitura/Package.swift
  swift/perfect/Dockerfile
  swift/perfect/Package.swift
  swift/perfect/main.swift
  swift/vapor/Package.swift
Labels: language:swift

#430 Add Kore (#224)
  .travis.yml
  FRAMEWORKS.yml
  c/kore/Dockerfile
  c/kore/hello/.gitignore
  c/kore/hello/conf/build.conf
  c/kore/hello/conf/hello.conf
  c/kore/hello/src/hello.c
  neph.yaml
Labels: language:c, pending

#515 Introduce chi
  .travis.yml
  FRAMEWORKS.yml
  go/chi/Dockerfile
  go/chi/go.mod
  go/chi/main.go
  neph.yaml
Labels: in-progress, language:go

#513 Switch to go modules
  go/beego/Dockerfile
  go/beego/go.mod
  go/echo/Dockerfile
  go/echo/go.mod
  go/fasthttprouter/Dockerfile
  go/fasthttprouter/go.mod
  go/gin/Dockerfile
  go/gin/go.mod
  go/gorilla-mux/Dockerfile
  go/gorilla-mux/go.mod
  go/muxie/Dockerfile
  go/muxie/go.mod
Labels: language:go, pending

#516 Update neph to 0.2.8
  .travis.yml
  neph.yaml
  php/symfony/config/packages/framework.yaml
  php/symfony/config/routes.yaml
  shard.yml
Labels: language:crystal, pending

#535 upgrade vapor from 3.0 to 3.1
  swift/kitura/Package.swift
  swift/perfect/Package.swift
  swift/vapor/Package.swift
Labels: language:swift, pending

#537 Remove redundant code
  go/chi/main.go
  go/echo/main.go
  go/gin/main.go
Labels: language:go, pending

#540 Introduce falcon
  .travis.yml
  FRAMEWORKS.yml
  neph.yaml
  python/falcon/Dockerfile
  python/falcon/requirements.txt
  python/falcon/server.py
Labels: language:python, pending
