Repository the-benchmarker/web-frameworks, pull requests merged in 2019-01, with the labels that each got.

#749 Add Muneem node framework
  .travis.yml
  FRAMEWORKS.yml
  neph.yaml
  node/muneem/Dockerfile
  node/muneem/app.js
  node/muneem/package.json
Labels: in-review, language:javascript

#768 Disable logging on Rocket
  rust/rocket/src/main.rs
Labels: language:rust

#801 upgrade chi to 4.0
  FRAMEWORKS.yml
  go/chi/go.mod
Labels: language:go

#664 Enable starlette / responder
  FRAMEWORKS.yml
  README.md
  rust/actix-web/Cargo.toml
  rust/gotham/Cargo.toml
  rust/iron/Cargo.toml
  rust/nickel/Cargo.toml
  rust/rocket/Cargo.toml
Labels: in-progress, language:python
