Repository the-benchmarker/web-frameworks, pull requests merged in 2019-08, with the labels that each got.

#1542 [C++] Add the Drogon framework
  .travis.yml
  README.md
  cpp/drogon/CMakeLists.txt
  cpp/drogon/Dockerfile
  cpp/drogon/cmake_modules/FindDrogon.cmake
  cpp/drogon/cmake_modules/FindJsoncpp.cmake
  cpp/drogon/config.json
  cpp/drogon/config.yaml
  cpp/drogon/controllers/BenchmarkCtrl.cc
  cpp/drogon/controllers/BenchmarkCtrl.h
  cpp/drogon/controllers/UserCtrl.cc
  cpp/drogon/controllers/UserCtrl.h
  cpp/drogon/main.cc
  cpp/evhtp/Dockerfile
  crystal/lucky/static/js/app.js
  python/masonite/app/http/controllers/PageController.py
Labels: language:cpp

#1636 [Javascript] Update nanoexpress to latest and improve performance
  node/nanoexpress/app.js
  node/nanoexpress/package.json
Labels: language:javascript

#1662 [C++] Update drogon to 1.0.0-beta6
  cpp/drogon/CMakeLists.txt
  cpp/drogon/Dockerfile
  cpp/drogon/cmake_modules/FindDrogon.cmake
  cpp/drogon/cmake_modules/FindJsoncpp.cmake
Labels: language:cpp

#1675 [Go] Introduce gramework
  .travis.yml
  go/gramework/Dockerfile
  go/gramework/config.yaml
  go/gramework/go.mod
  go/gramework/main.go
Labels: language:go, status:pending-approval

#1680 [Go] Add RTE
  .dependabot/config.yml
  .travis.yml
  go/rte/Dockerfile
  go/rte/config.yaml
  go/rte/go.mod
  go/rte/main.go
Labels: language:go

#1685 [Go] Add Air
  .dependabot/config.yml
  .travis.yml
  go/air/Dockerfile
  go/air/config.yaml
  go/air/go.mod
  go/air/main.go
Labels: language:go

#1710 [Javascript] Remove nanoexpress
  .dependabot/config.yml
  .travis.yml
  node/nanoexpress/Dockerfile
  node/nanoexpress/app.js
  node/nanoexpress/config.yaml
  node/nanoexpress/package.json
Labels: language:javascript

#1715 [Javascript] Add iotjs-express
  .dependabot/config.yml
  .travis.yml
  node/iotjs-express/Dockerfile
  node/iotjs-express/app.js
  node/iotjs-express/config.yaml
  node/iotjs-express/package.json
Labels: language:javascript

#1721 Updating tornado handler to return 200 only with empty response
  python/tornado/server.py
Labels: language:python
